workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: 3.29.3
      android_signing:
        - keystore_reference
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com

  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: 3.29.3
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Debug APK
        script: flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
